# Generated by Django 4.1.3 on 2022-11-27 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_request_headers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='modified',
        ),
    ]
